zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom reset: edit.zoom_reset()
scroll up: edit.page_up()
scroll down: edit.page_down()
copy that: edit.copy()
cut that: edit.cut()
(pace | paste) that: edit.paste()
peace: edit.paste()
undo that: edit.undo()
redo that: edit.redo()
paste match: edit.paste_match_style()
disc | file save: edit.save()
padding: user.insert_between(" ", " ")
slap: edit.line_insert_down()
pour: edit.line_insert_down()
drink: edit.line_insert_up()
